version: "2"
services:
  plone:
    image: plone:5
    ports:
    - "8080"
    volumes:
    - ../../:/plone/instance/src/eea.dexterity.indicators
    environment:
      ADDONS: "eea.dexterity.indicators[test]"
      DEVELOP: "src/eea.dexterity.indicators"
